---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: master/index.html
  label: index
- type: document
  path: master/about-me.html
  label: about-me
- type: document
  path: master/kmo-resume.pdf
  label: resume
  read_only: true
- type: heading
  label: Projects
- type: document
  path: master/arl.html
  label: arl
- type: document
  path: blob/master/a11y.html
  label: a11y
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
